# Cloudflare Workers configuration for Local Fishing Backend
name = "local-fishing-backend"
main = "src/index.ts"
compatibility_date = "2025-07-10"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[build]
command = ""



# Production environment variables (will be set via wrangler secrets)
# These are placeholders - actual values should be set using:
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_ANON_KEY
# etc.

# Default environment variables for development
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"

# These values will be overridden by environment variables in production
# Use wrangler secret to set these in production:
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_ANON_KEY
# wrangler secret put SUPABASE_SERVICE_ROLE_KEY
# etc.
CORS_ORIGIN = "http://localhost:5000,http://localhost:8080,http://localhost:5173,http://localhost:3000,https://local-fishing-frontend.pages.dev,https://local-fishing-frontend-preview.pages.dev"
MAX_FILE_SIZE = "10485760"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"

# Development environment (for local testing)
[env.development]
name = "local-fishing-backend-dev"

# Production environment
[env.production]
name = "local-fishing-backend-prod"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
# Production secrets should be set via wrangler secret put commands

# Rate limiting configuration
[[env.production.durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"
