# Cloudflare Workers configuration for Local Fishing Backend
name = "local-fishing-backend"
main = "src/index.ts"
compatibility_date = "2025-07-10"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[build]
command = ""



# Production environment variables (will be set via wrangler secrets)
# These are placeholders - actual values should be set using:
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_ANON_KEY
# etc.

# Default environment variables for development
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
SUPABASE_URL = "https://irxbpmlcqvmivlafoivt.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeGJwbWxjcXZtaXZsYWZvaXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjIwNjUsImV4cCI6MjA3MzkzODA2NX0.a0i_Edhu8SANJzAdTV2nx6FLoaJJ1n-sNUBsugFJwgY"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeGJwbWxjcXZtaXZsYWZvaXZ0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODM2MjA2NSwiZXhwIjoyMDczOTM4MDY1fQ.dps-iEltfrpKWAUl0fiEUWcNSZxFd0Oaec-J-OyDB70"
JWT_SECRET = "your_super_secret_jwt_key_here_make_it_at_least_32_characters_long"
JWT_EXPIRES_IN = "7d"
JWT_REFRESH_SECRET = "your_refresh_secret_here_also_make_it_32_characters_long"
JWT_REFRESH_EXPIRES_IN = "30d"
CORS_ORIGIN = "http://localhost:5000,http://localhost:8080,http://localhost:5173,http://localhost:3000,https://local-fishing-frontend.pages.dev,https://local-fishing-frontend-preview.pages.dev"
MAX_FILE_SIZE = "10485760"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "587"
EMAIL_USER = "automatedinventorymessage@gmail.com"
EMAIL_PASSWORD = "wzge fkwj unyk xkiw"
EMAIL_FROM = "automatedinventorymessage@gmail.com"
CLOUDINARY_CLOUD_NAME = "dji23iymw"
CLOUDINARY_API_KEY = "162843632338622"
CLOUDINARY_API_SECRET = "pB_7QOUVorneWKAer1aErW-yNe0"

# Development environment (for local testing)
[env.development]
name = "local-fishing-backend-dev"

# Production environment
[env.production]
name = "local-fishing-backend-prod"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
# Production secrets should be set via wrangler secret put commands

# Rate limiting configuration
[[env.production.durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

# KV namespace for caching (optional)
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"
